### PR TITLE
Always "trigger change" on county element

### PR DESCRIPTION
**Pull request by y3kdaniel**
#15

### CODE REVIEW

**Comment by veda-consulting** [comment]
@y3kdaniel can you provide a bit more info on the issue and resolution? We'd love to include it if we can understand why its needed. Thanks

**Comment by y3kdaniel** [comment]
The full detail was posted in my initial issue report, with my resolution added as a comment, which can be found here: #15

**Comment by y3kdaniel** [comment]
But the basic version is, that without this patch, the module sets the form County value to null (or '') but unless the returned address includes a county it does not trigger the displayed County to update.
Adding the trigger to a separate line outside of the if statement means that the displayed County will be updated either to show no county or the county returned in the lookup, if there is one returned.
(CiviPostcode won't return a county as the PAF file does not include them)

**Comment by mattwire** [comment]
@veda-consulting This can now be closed, as it's included in #21

**Comment by veda-consulting** [comment]
closed, as it's included in [#21](https://github.com/veda-consulting/uk.co.vedaconsulting.module.civicrmpostcodelookup/pull/21)

**Pull request closed without merging**
